# Form implementation generated from reading ui file 'c:\Users\venous\Desktop\management\StoreManagement\GUI\Yashar\ProductManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_productManager(object):
    def setupUi(self, productManager):
        productManager.setObjectName("productManager")
        productManager.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=productManager)
        self.centralwidget.setObjectName("centralwidget")
        self.loginLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.loginLabel.setGeometry(QtCore.QRect(120, 30, 381, 101))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(16)
        self.loginLabel.setFont(font)
        self.loginLabel.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.loginLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.loginLabel.setLineWidth(3)
        self.loginLabel.setMidLineWidth(2)
        self.loginLabel.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.loginLabel.setScaledContents(False)
        self.loginLabel.setWordWrap(False)
        self.loginLabel.setObjectName("loginLabel")
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(180, 330, 75, 24))
        self.loginButton.setObjectName("loginButton")
        self.unBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.unBox.setGeometry(QtCore.QRect(10, 200, 251, 51))
        self.unBox.setObjectName("unBox")
        self.passBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.passBox.setGeometry(QtCore.QRect(10, 270, 251, 51))
        self.passBox.setObjectName("passBox")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 180, 80, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 49, 16))
        self.label_2.setObjectName("label_2")
        productManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=productManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        productManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=productManager)
        self.statusbar.setObjectName("statusbar")
        productManager.setStatusBar(self.statusbar)

        self.retranslateUi(productManager)
        QtCore.QMetaObject.connectSlotsByName(productManager)

    def retranslateUi(self, productManager):
        _translate = QtCore.QCoreApplication.translate
        productManager.setWindowTitle(_translate("productManager", "MainWindow"))
        self.loginLabel.setText(_translate("productManager", "Please Log in to your Account"))
        self.loginButton.setText(_translate("productManager", "Log in"))
        self.unBox.setHtml(_translate("productManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.passBox.setHtml(_translate("productManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("productManager", "Username"))
        self.label_2.setText(_translate("productManager", "Password"))
