# Form implementation generated from reading ui file 'c:\Users\venous\Desktop\management\StoreManagement\GUI\Yashar\SalesManagement.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SalesManagement(object):
    def setupUi(self, SalesManagement):
        SalesManagement.setObjectName("SalesManagement")
        SalesManagement.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=SalesManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(-20, 0, 601, 641))
        self.listView.setObjectName("listView")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 561, 330))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 443, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 440, 140, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 440, 140, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 420, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 420, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 250, 16))
        font = QtGui.QFont()
        font.setFamily("Swis721 BlkEx BT")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 40, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        SalesManagement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SalesManagement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        SalesManagement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SalesManagement)
        self.statusbar.setObjectName("statusbar")
        SalesManagement.setStatusBar(self.statusbar)

        self.retranslateUi(SalesManagement)
        QtCore.QMetaObject.connectSlotsByName(SalesManagement)

    def retranslateUi(self, SalesManagement):
        _translate = QtCore.QCoreApplication.translate
        SalesManagement.setWindowTitle(_translate("SalesManagement", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SalesManagement", "SalesBill"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SalesManagement", "BuyedBill"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SalesManagement", "Update"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SalesManagement", "Delete"))
        self.pushButton.setText(_translate("SalesManagement", "Add"))
        self.label.setText(_translate("SalesManagement", "SalesBill"))
        self.label_2.setText(_translate("SalesManagement", "BuyedBill"))
        self.label_3.setText(_translate("SalesManagement", "SalesManagement"))
        self.pushButton_2.setText(_translate("SalesManagement", "Back"))
