# Form implementation generated from reading ui file 'c:\Users\venous\Desktop\for qt\manangment\pages\signupPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_signInPage(object):
    def setupUi(self, signInPage):
        signInPage.setObjectName("signInPage")
        signInPage.resize(375, 465)
        signInPage.setMaximumSize(QtCore.QSize(480, 620))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/product.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        signInPage.setWindowIcon(icon)
        signInPage.setStyleSheet("background-color: rgb(0, 77, 113);")
        signInPage.setIconSize(QtCore.QSize(55, 55))
        self.centralwidget = QtWidgets.QWidget(parent=signInPage)
        self.centralwidget.setObjectName("centralwidget")
        self.labelUn = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUn.setGeometry(QtCore.QRect(130, 120, 94, 20))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        font.setBold(False)
        self.labelUn.setFont(font)
        self.labelUn.setStyleSheet("font-size:14pt;")
        self.labelUn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelUn.setObjectName("labelUn")
        self.labelPass = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPass.setGeometry(QtCore.QRect(130, 190, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        font.setBold(False)
        self.labelPass.setFont(font)
        self.labelPass.setStyleSheet("font-size:14pt;")
        self.labelPass.setObjectName("labelPass")
        self.signuppb = QtWidgets.QPushButton(parent=self.centralwidget)
        self.signuppb.setGeometry(QtCore.QRect(150, 330, 75, 24))
        self.signuppb.setObjectName("signuppb")
        self.labelUn_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUn_2.setGeometry(QtCore.QRect(100, 260, 170, 20))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        font.setBold(False)
        self.labelUn_2.setFont(font)
        self.labelUn_2.setStyleSheet("font-size:14pt;")
        self.labelUn_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelUn_2.setObjectName("labelUn_2")
        self.Backpb = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Backpb.setGeometry(QtCore.QRect(0, 0, 75, 24))
        self.Backpb.setObjectName("Backpb")
        self.usernameLE = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameLE.setGeometry(QtCore.QRect(70, 150, 221, 22))
        self.usernameLE.setObjectName("usernameLE")
        self.passwordLE = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordLE.setGeometry(QtCore.QRect(70, 220, 221, 22))
        self.passwordLE.setObjectName("passwordLE")
        self.repeatPasswordLE = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.repeatPasswordLE.setGeometry(QtCore.QRect(70, 290, 221, 22))
        self.repeatPasswordLE.setObjectName("repeatPasswordLE")
        signInPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=signInPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 22))
        self.menubar.setObjectName("menubar")
        signInPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=signInPage)
        self.statusbar.setObjectName("statusbar")
        signInPage.setStatusBar(self.statusbar)

        self.retranslateUi(signInPage)
        QtCore.QMetaObject.connectSlotsByName(signInPage)

    def retranslateUi(self, signInPage):
        _translate = QtCore.QCoreApplication.translate
        signInPage.setWindowTitle(_translate("signInPage", "StoreManagement"))
        self.labelUn.setText(_translate("signInPage", "<html><head/><body><p align=\"center\">Username</p></body></html>"))
        self.labelPass.setText(_translate("signInPage", "<html><head/><body><p align=\"center\">Password</p></body></html>"))
        self.signuppb.setText(_translate("signInPage", "sign up"))
        self.labelUn_2.setText(_translate("signInPage", "<html><head/><body><p align=\"center\">Repeat Password</p></body></html>"))
        self.Backpb.setText(_translate("signInPage", "Back"))
